-- Minimum Supabase schema for the restored hackathon demo.
-- Review before applying to an existing Supabase project.

CREATE TABLE IF NOT EXISTS public.account_details (
  id text PRIMARY KEY,
  type text NOT NULL CHECK (type IN ('admin', 'faculty')),
  name text NOT NULL DEFAULT '',
  email text NOT NULL UNIQUE,
  "avatarUrl" text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profile_details (
  id text PRIMARY KEY REFERENCES public.account_details(id) ON DELETE CASCADE,
  profession text,
  description text,
  status text NOT NULL DEFAULT 'accepted',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.educational_background (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES public.account_details(id) ON DELETE CASCADE,
  degree text NOT NULL DEFAULT '',
  institution text NOT NULL DEFAULT '',
  "startDate" text,
  "endDate" text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.work_experiences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES public.account_details(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT '',
  organization text NOT NULL DEFAULT '',
  period text NOT NULL DEFAULT '',
  details text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.professional_development (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES public.account_details(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT '',
  organization text NOT NULL DEFAULT '',
  period text NOT NULL DEFAULT '',
  details text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES public.account_details(id) ON DELETE CASCADE,
  document_type text NOT NULL DEFAULT 'Others',
  file_name text NOT NULL,
  status text NOT NULL DEFAULT 'Pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  submitted_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL DEFAULT 'SYSTEM',
  action text NOT NULL,
  details text,
  timestamp timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS account_details_type_idx ON public.account_details(type);
CREATE INDEX IF NOT EXISTS educational_background_user_id_idx ON public.educational_background(user_id);
CREATE INDEX IF NOT EXISTS work_experiences_user_id_idx ON public.work_experiences(user_id);
CREATE INDEX IF NOT EXISTS professional_development_user_id_idx ON public.professional_development(user_id);
CREATE INDEX IF NOT EXISTS submissions_user_status_idx ON public.submissions(user_id, status);
CREATE INDEX IF NOT EXISTS submissions_submitted_at_idx ON public.submissions(submitted_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_timestamp_idx ON public.audit_logs(timestamp DESC);
