export const PUBLIC_OG_FILES = [
  'og-image.png',
  'og/admin.png',
  'og/approvals.png',
  'og/faculty.png',
  'og/landing.png',
  'og/login.png',
  'og/preview.png',
  'og/profile.png',
  'og/register.png',
  'og/theme.png',
  'og/upload.png',
  'og/uploaded-files.png',
  'og/web-vitals.png',
  'og/workflow.png',
]

export const OG_IMAGE_ALTS = {
  'og-image.png': 'CCIS Smart Faculty Profile Management System public demo with the college seal and landing page',
  'og/landing.png': 'CCIS Smart Faculty Profile Management System public demo with the college seal and landing page',
  'og/workflow.png': 'Hackathon workflow still: upload, review, and approve sample credentials',
  'og/login.png': 'Seeded faculty and admin demo login for the CCIS public showcase',
  'og/register.png': 'Browser-local faculty registration for the CCIS public showcase',
  'og/faculty.png': 'Faculty workspace with metrics and smart upload for Dr. Maria Santos',
  'og/upload.png': 'Smart upload of a generated sample certificate in the faculty workspace',
  'og/uploaded-files.png': 'Faculty uploaded-files table with status chips and row actions',
  'og/profile.png': 'Faculty profile builder and biography draft from approved credentials',
  'og/admin.png': 'Admin reviewer dashboard with metrics, charts, and pending submissions',
  'og/approvals.png': 'Admin approval queue with Approve, Return, and View actions',
  'og/theme.png': 'Faculty workspace in light mint and dark green-black CCIS chrome',
  'og/web-vitals.png': 'Landing page Core Web Vitals panel showing local session metrics',
  'og/preview.png': 'Demo file preview for generated sample credentials',
}

export const FALLBACK_OG_IMAGE = {
  '404.html': 'og-image.png',
  'admin/accounts/index.html': 'og/admin.png',
  'admin/approvals/index.html': 'og/approvals.png',
  'admin/audit-logs/index.html': 'og/admin.png',
  'admin/dashboard/index.html': 'og/admin.png',
  'admin/help/index.html': 'og/admin.png',
  'admin/reports/index.html': 'og/admin.png',
  'admin/settings/index.html': 'og/admin.png',
  'auth/login/index.html': 'og/login.png',
  'auth/register/index.html': 'og/register.png',
  'demo-storage/index.html': 'og/preview.png',
  'faculty/dashboard/index.html': 'og/faculty.png',
  'faculty/profile/index.html': 'og/profile.png',
  'faculty/settings/index.html': 'og/faculty.png',
  'faculty/uploaded/index.html': 'og/uploaded-files.png',
}
